// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.175
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectReferenceContextMenuExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidProjectReferenceContextMenuExtensionCommandPackageString = "beb53dc5-2021-44c9-97dd-8cf38e02e4c4";
        public const string guidProjectReferenceContextMenuExtensionCommandPackageCmdSetString = "866c9883-9b23-4d2a-a8d1-c26984ef526b";
        public const string guidImagesString = "efe16d93-0646-4c6c-bd52-7cfa345c3f0e";
        public const string guidProjectReferenceContextMenuExtensionCommandPackageCmdSet1String = "8fdac97d-17b5-46ea-b9d4-8d12d246d495";
        public const string guidImages1String = "3769888c-8a0d-4328-94bb-d8eb5badab58";
        public const string guidProjectReferenceContextMenuExtensionCommandPackageCmdSet2String = "981526f6-9a39-4ce4-a008-cb352aaf6294";
        public const string guidImages2String = "6e8464b0-9e01-4834-9294-07aa912fec0e";
        public static Guid guidProjectReferenceContextMenuExtensionCommandPackage = new Guid(guidProjectReferenceContextMenuExtensionCommandPackageString);
        public static Guid guidProjectReferenceContextMenuExtensionCommandPackageCmdSet = new Guid(guidProjectReferenceContextMenuExtensionCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
        public static Guid guidProjectReferenceContextMenuExtensionCommandPackageCmdSet1 = new Guid(guidProjectReferenceContextMenuExtensionCommandPackageCmdSet1String);
        public static Guid guidImages1 = new Guid(guidImages1String);
        public static Guid guidProjectReferenceContextMenuExtensionCommandPackageCmdSet2 = new Guid(guidProjectReferenceContextMenuExtensionCommandPackageCmdSet2String);
        public static Guid guidImages2 = new Guid(guidImages2String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int VersionCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        //public const int MyMenuGroup = 0x1020;
        public const int cmdidNuGetCommand = 0x0100;
        //public const int bmpPic1 = 0x0001;
        //public const int MyMenuGroup = 0x1020;
        public const int cmdidStackOverflowCommand = 0x0100;
        //public const int bmpPic1 = 0x0001;
    }
}
