// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.175
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectReferenceContextMenuExtension
{
				static class Vsix
				{
								public const string Id = "f8b219f9-f168-481a-b73b-b85d79eceb7b";
								public const string Name = "Project Reference Context Menu Extension";
								public const string Description = "Adds context menu items to project reference to quickly open NuGet, Stack Overflow, etc for one or more references.";
								public const string Language = "en-US";
								public const string Version = "1.0";
								public const string Author = "Matt Burleigh";
								public const string Tags = "visual studio, nuget, stack overflow";
				}
}
